baseURL = "https://perl.com/"
languageCode = "en-us"
title = "Perl.com - programming news, code and culture"
paginate = 20
disablePathToLower = true
pygmentsCodeFences = true
pygmentsStyle = "monokai"
rssLimit = 25

[taxonomies]
author = "authors"
tag = "tags"
category = "categories"

[permalinks]
legacy=":slug"

[params]
github="https://github.com/tpf/perldotcom"
description = "Since 1997 Perl.com has published articles about the Perl programming language, its culture and community."
