baseurl = "http://perl.com/"
languageCode = "en-us"
title = "Perl programming news, code and culture"
paginate = 30
[taxonomies]
author = "authors"
tag = "tags"
category = "categories"
[permalinks]
article=":slug"
