name: Spell checking
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '5 * * * *'

jobs:
  build:
    name: Spell checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: check-spelling/check-spelling@0.0.17-alpha
      - uses: ./
          with:
          bucket: .github/actions
          project: spelling
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
